name: Generate 3D Contribution Graph

on:
  # 毎日0時（UTC）に自動実行
  schedule:
    - cron: "0 0 * * *"
  # 手動実行も可能にする
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Generate 3D contrib images
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          # 公開リポだけならこれで十分
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output                  # output にだけ書き出す
          build_dir: ./profile-3d-contrib        # このディレクトリの中身を出す
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
